#!/usr/bin/env bash
#
# add a new package
# 
# ./add-package package-url package-name 

add() {
	local url=$1
	local name=$2
	git submodule add $url pack/gmcwilliams/start/$name
}

add $1 $2

git add .gitmodules

