#!/usr/bin/env bash
#
# add a new package
# 
# ./add-package package-name package-url

add() {
	local name=$1
	local url=$2
	git submodule add $url pack/gmcwilliams/start/$name
	git add pack/gmcwilliams/start/$name
}

add $1 $2

git add .gitmodules

