#!/usr/bin/env bash
#

add() {
	local name=$2
	local url=$1
	git submodule add $url pack/gmcwilliams/start/$name
#	git add pack/gmcwilliams/start/$name
}

#add https://github.com/pearofducks/ansible-vim.git ansible-vim
#add https://github.com/ctrlpvim/ctrlp.vim.git ctrlp.vim 
#add https://github.com/tpope/vim-fugitive.git fugitive 
#add https://github.com/scrooloose/nerdtree.git nerdtree 
#add https://github.com/scrooloose/nerdtree-git-plugin.git nerdtree-git-plugin 
#add https://github.com/tpope/vim-unimpaired.git  unimpaired 
#add https://github.com/vim-airline/vim-airline.git vim-airline 
#add https://github.com/altercation/vim-colors-solarized.git vim-colors-solarized 

